This patch adds the new mechanism of compiling the brisa framework. Now, we can compile the framework under linux and windows, mac os is still a work in progress.
git-svn-id: https://vcs.maemo.org/svn/brisa/qt/trunk/qt-brisa@2155 0dea1104-2826-0410-b20c-9c2201499e24

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,115 +1,210 @@
 #!/bin/bash
 
-#====some defaults====
+# defaults
 QMAKE_BIN=qmake
 WHICH=which
+BRISA_MODULES="core upnp utils"
+BRISA_INSTALL_PREFIX="/usr"
 
-NO_DB=0
-NO_FFMPEG=0
-NO_XSS=0
-NO_ZEROCONF=0
-
+# detect platform
 if uname -a | grep -iq Darwin; then
+    BRISA_MAC=1
     DEFAULT_LIBS="/Library/Frameworks"
     QMAKE_PARAMS="-spec macx-g++"
-    NO_XSS=1
+    NO_XRANDR=1
 else
+    BRISA_MAC=0
     DEFAULT_LIBS="PREFIX/lib"
     QMAKE_PARAMS=""
 fi
 
-# the directory of this script (the root)
-PROJECT_ROOT=`dirname $0`
-PROJECT_ROOT=`(cd "$relpath"; /bin/pwd)`
-TESTDIR=$PROJECT_ROOT/config.tests
-CONFIG_LOG=$PROJECT_ROOT/config.log
+# working directories
+BRISA_SOURCE_TREE=`dirname $0`
+BRISA_SOURCE_TREE=`(cd "$BRISA_SOURCE_TREE"; /bin/pwd)`
+BRISA_BUILD_TREE=`/bin/pwd`
+#[ ! -d $BRISA_BUILD_TREE/examples ] && mkdir $BRISA_BUILD_TREE/examples
+[ ! -d $BRISA_BUILD_TREE/tests ] && mkdir $BRISA_BUILD_TREE/tests
 
-# Define some colors for neat output
+# output files
+CONFIG_LOG=$BRISA_BUILD_TREE/config.log
+QMAKE_CACHE=$BRISA_BUILD_TREE/.qmake.cache
+BRISA_VARS=$BRISA_BUILD_TREE/features/brisavars.prf
+[ -f $CONFIG_LOG ] && mv $CONFIG_LOG $CONFIG_LOG.bak
+[ -f $QMAKE_CACHE ] && mv $QMAKE_CACHE $QMAKE_CACHE.bak
+[ -f $BRISA_VARS ] && mv $BRISA_VARS $BRISA_VARS.bak
+
+# colors
 C_RED='\e[1;31m'
 C_BLUE='\e[1;34m'
 C_GREEN='\e[1;32m'
 C_CYAN='\e[1;36m'
-C_NONE='\e[0m' # No Color
+C_NONE='\e[0m'
 
-#====parse configure options====
+# defaults
+echo "CONFIG += silent" > $QMAKE_CACHE
+echo "BRISA_MODULES = $BRISA_MODULES" >> $QMAKE_CACHE
+echo "BRISA_MODULES = $BRISA_MODULES" > $BRISA_VARS
 
-echo "CONFIG += silent" > config.in
-
+# parse configure options
 while (( $# > 0 )); do
     if [ $1 == "-qmake-bin" ]; then
         QMAKE_BIN=$2; shift
+    elif [ $1 == "-L" ]; then
+        echo "LIBS += -L$2" >> $QMAKE_CACHE;shift
+    elif [ $1 == "-l" ]; then
+        echo "LIBS += -l$2" >> $QMAKE_CACHE;shift
+    elif [ $1 == "-I" ]; then
+        echo "INCLUDEPATH += $2" >> $QMAKE_CACHE;shift
     elif [ $1 == "-bootstrap" ]; then
-        echo "CONFIG += bootstrap" >> config.in; shift
+        echo "CONFIG += bootstrap" >> $QMAKE_CACHE; shift
+    elif [ $1 == "-nomake" ]; then
+        echo "BRISA_MODULES -= $2" >> $QMAKE_CACHE
+        echo "BRISA_MODULES -= $2" >> $BRISA_VARS; shift
     elif [ $1 == "-prefix" ]; then
-        echo "BRISAINSTALLDIR = $2" >> config.in; shift
+        BRISA_INSTALL_PREFIX=$2; shift
     elif [ $1 == "-libdir" ]; then
-        echo "target.path = $2" >> config.in; shift
+        BRISA_INSTALL_LIBS=$2; shift
     elif [ $1 == "-docdir" ]; then
-        echo "docs.path = $2" >> config.in; shift
+        BRISA_INSTALL_DOCS=$2; shift
     elif [ $1 == "-headerdir" ]; then
-        echo "include.path = $2" >> config.in; shift
+        BRISA_INSTALL_HEADERS=$2; shift
     elif [ $1 == "-bindir" ]; then
-        echo "bin.path = $2" >> config.in; shift
+        BRISA_INSTALL_BINS=$2; shift
+    elif [ $1 == "-featuredir" ]; then
+        BRISA_INSTALL_FEATURES=$2; shift
     elif [ $1 == "-static" ]; then
-        echo "CONFIG += static staticlib" >> config.in
+        echo "CONFIG += static staticlib" >> $QMAKE_CACHE
+        echo "DEFINES += BRISA_STATIC" >> $BRISA_VARS
     elif [ $1 == "-debug" ]; then
-        echo "CONFIG += debug" >> config.in
+        echo "CONFIG += debug" >> $QMAKE_CACHE
+        echo "BRISA_INSTALL_TYPE = debug" >> $BRISA_VARS
     elif [ $1 == "-release" ]; then
-        echo "CONFIG += release" >> config.in
+        echo "CONFIG += release" >> $QMAKE_CACHE
+        echo "BRISA_INSTALL_TYPE = release" >> $BRISA_VARS
     elif [ $1 == "-verbose" ]; then
-        echo "CONFIG -= silent" >> config.in
+        echo "CONFIG -= silent" >> $QMAKE_CACHE
     elif [ $1 == "-qws" ]; then
-        echo "CONFIG += qws" >> config.in
+        echo "CONFIG += qws" >> $QMAKE_CACHE
     elif [ $1 == "-coverage" ]; then
-        echo "CONFIG += coverage" >> config.in
-    elif [ $1 == "-help" ] || [ $1 == "--help" ]; then
+        echo "CONFIG += coverage" >> $QMAKE_CACHE
+    elif [ $1 == "-universal" ]; then
+        echo "CONFIG += x86 ppc" >> $QMAKE_CACHE
+    elif [ $1 == "-arch" ]; then
+        echo "CONFIG += $2" >> $QMAKE_CACHE
+        shift
+    elif [ $1 == "-sdk" ]; then
+        echo "QMAKE_MAC_SDK=$2" >> $QMAKE_CACHE; shift
+    elif [ $1 == "-h" ] || [ $1 == "-help" ] || [ $1 == "--help" ]; then
         echo "Usage: configure [-prefix <dir>] [-libdir <dir>] [-docdir <dir>]"
-        echo "       [-bindir <dir>] [-headerdir <dir>] [-qmake-bin <path>]"
-        echo "       [-static] [-debug] [-release] [-no-db] [-no-xss]"
-        echo "       [-verbose] [-qws]"
+        echo "       [-bindir <dir>] [-headerdir <dir>] [-featuredir <dir> ]"
+        echo "       [-qmake-bin <path>] [-static] [-debug] [-release]"
+        echo "       [-nomake <module>]"
+        if [[ "$BRISA_MAC" == "0" ]]; then
+            echo -n "       [-no-xrandr] [-qws]"
+        else
+            echo -n "       [-universal] [-arch <arch>] [-sdk <path>]"
+        fi
+        echo " [-verbose] [-coverage]"
         echo
         echo "Installation options:"
         echo
         echo "-prefix <dir> ....... This will install everything relative to <dir>"
-        echo "                      default: /usr/local/brisa"
+        echo "                      default: /usr/local/BRisa"
         echo "-libdir <dir> ....... Libraries will be installed to <dir>"
         echo "                      default: $DEFAULT_LIBS"
         echo "-docdir <dir> ....... Documentation will be installed to <dir>"
-        echo "                      default: PREFIX/share/doc"
+        echo "                      default: PREFIX/doc"
         echo "-bindir <dir> ....... Executables will be installed to <dir>"
         echo "                      default: PREFIX/bin"
         echo "-headerdir <dir> .... Include files will be installed to <dir>"
         echo "                      default: PREFIX/include"
+        echo "-featuredir <dir> ... Feature files will be installed to <dir>"
+        echo "                      default: QMAKE_MKSPECS/features"
         echo "-qmake-bin <path> ... Specifies the path to the qmake executable"
         echo "                      default: search the system path"
-        echo "-static ............. Compile BRisa as a static library"
+        echo "-L <path> ........... Specifies the a additional library search path"
+        echo "-I <path> ........... Specifies the a additional include search path"
+        echo "-l <path> ........... Add a custom library"
+        echo "-static ............. Build BRisa as a static library"
         echo "-debug .............. Build BRisa with debugging symbols"
         echo "-release ............ Build BRisa without debugging support"
-        echo "-verbose ............ shows compiler output"
-        echo "-qws ................ Build for Qt/Embedded"
+        if [[ "$BRISA_MAC" != "1" ]]; then
+            echo "-qws ................ Build for Qt/Embedded"
+        fi
+        echo "-nomake <module> .... Do not compile the specified module"
+        echo "                      options: $BRISA_MODULES"
+        echo "-verbose ............ Show full compiler output"
         echo "-coverage ........... Collect coverage information"
+        if [[ "$BRISA_MAC" == "1" ]]; then
+            echo "-universal .......... Equivalent to -arch ppc -arch x86"
+            echo "-arch <arch> ........ Include <arch> in universal binary"
+            echo "-sdk <path> ......... Use a different Mac SDK"
+        fi
 
-        rm config.in
+        [ -f $CONFIG_LOG.bak ] && mv $CONFIG_LOG.bak $CONFIG_LOG
+        [ -f $QMAKE_CACHE.bak ] && mv $QMAKE_CACHE.bak $QMAKE_CACHE
+        [ -f $BRISA_VARS.bak ] && mv $BRISA_VARS.bak $BRISA_VARS
         exit
     else
         echo "Unrecognized configure option: $1"
-        rm config.in
+        [ -f $CONFIG_LOG.bak ] && mv $CONFIG_LOG.bak $CONFIG_LOG
+        [ -f $QMAKE_CACHE.bak ] && mv $QMAKE_CACHE.bak $QMAKE_CACHE
+        [ -f $BRISA_VARS.bak ] && mv $BRISA_VARS.bak $BRISA_VARS
         exit
     fi
     shift
 done
 
-#====begin some autodetection====
->$CONFIG_LOG
-
-# qmake?
+# detect qmake
 if ! $WHICH $QMAKE_BIN >>$CONFIG_LOG 2>&1; then
     echo >&2 "You don't seem to have 'qmake' in your PATH."
     echo >&2 "Cannot proceed."
     exit 1
 fi
 
-# find a make command
+# default directories
+if [[ "$BRISA_INSTALL_PREFIX" == "" ]]; then
+    BRISA_INSTALL_PREFIX="/usr/local/brisa"
+fi
+if [[ "$BRISA_INSTALL_LIBS" == "" ]]; then
+    if [[ "$BRISA_MAC" == "1" ]]; then
+        BRISA_INSTALL_LIBS="/Library/Frameworks"
+    else
+        BRISA_INSTALL_LIBS="$BRISA_INSTALL_PREFIX/lib"
+    fi
+fi
+if [[ "$BRISA_INSTALL_DOCS" == "" ]]; then
+    BRISA_INSTALL_DOCS="$BRISA_INSTALL_PREFIX/doc"
+fi
+if [[ "$BRISA_INSTALL_HEADERS" == "" ]]; then
+    BRISA_INSTALL_HEADERS="$BRISA_INSTALL_PREFIX/include/BRisa"
+fi
+if [[ "$BRISA_INSTALL_BINS" == "" ]]; then
+    BRISA_INSTALL_BINS="$BRISA_INSTALL_PREFIX/bin"
+fi
+if [[ "$BRISA_INSTALL_FEATURES" == "" ]]; then
+    BRISA_INSTALL_FEATURES=`$QMAKE_BIN -query QMAKE_MKSPECS`
+    BRISA_INSTALL_FEATURES="$BRISA_INSTALL_FEATURES/features"
+fi
+
+# output variables
+echo "BRISA_INSTALL_PREFIX = $BRISA_INSTALL_PREFIX" >> $QMAKE_CACHE
+echo "BRISA_INSTALL_PREFIX = $BRISA_INSTALL_PREFIX" >> $BRISA_VARS
+echo "BRISA_INSTALL_LIBS = $BRISA_INSTALL_LIBS" >> $QMAKE_CACHE
+echo "BRISA_INSTALL_LIBS = $BRISA_INSTALL_LIBS" >> $BRISA_VARS
+echo "BRISA_INSTALL_BINS = $BRISA_INSTALL_BINS" >> $QMAKE_CACHE
+echo "BRISA_INSTALL_BINS = $BRISA_INSTALL_BINS" >> $BRISA_VARS
+echo "BRISA_INSTALL_HEADERS = $BRISA_INSTALL_HEADERS" >> $QMAKE_CACHE
+echo "BRISA_INSTALL_HEADERS = $BRISA_INSTALL_HEADERS" >> $BRISA_VARS
+echo "BRISA_INSTALL_FEATURES = $BRISA_INSTALL_FEATURES" >> $QMAKE_CACHE
+echo "BRISA_INSTALL_FEATURES = $BRISA_INSTALL_FEATURES" >> $BRISA_VARS
+echo "BRISA_INSTALL_DOCS = $BRISA_INSTALL_DOCS" >> $QMAKE_CACHE
+echo "BRISA_INSTALL_DOCS = $BRISA_INSTALL_DOCS" >> $BRISA_VARS
+echo "BRISA_SOURCE_TREE = $BRISA_SOURCE_TREE" >> $QMAKE_CACHE
+echo "BRISA_BUILD_TREE = $BRISA_BUILD_TREE" >> $QMAKE_CACHE
+
+# detect make
+echo>$CONFIG_LOG
 if [ -z "$MAKE" ]; then
     MAKE=
     for mk in gmake make; do
@@ -125,31 +220,26 @@ if [ -z "$MAKE" ]; then
     fi
 fi
 
+# detect dependencies
 configtest()
 {
-    echo -en "checking for $1\t"
+    echo -en "Checking for $1 "
     echo -e  " \n\n $1\n" >>$CONFIG_LOG
-    cd $TESTDIR/$1
-    $QMAKE_BIN $QMAKE_PARAMS  >>$CONFIG_LOG
+    mkdir -p "$BRISA_BUILD_TREE/config.tests/$1"
+    cd "$BRISA_BUILD_TREE/config.tests/$1"
+    $QMAKE_BIN $QMAKE_PARAMS "$BRISA_SOURCE_TREE/config.tests/$1/$1.pro" >>$CONFIG_LOG
     echo -n "."
-    $MAKE clean >>$CONFIG_LOG
+    $MAKE clean >>$CONFIG_LOG 2>&1
     [ -f ./$1 ] && rm ./$1
     echo -n "."
-    $MAKE >>$CONFIG_LOG
-    echo -n "."
-    if ./$1 >>$CONFIG_LOG ; then
-    	echo -e >&2 "  [${C_GREEN}success${C_NONE}] "
-    	echo "DEFINES+=HAVE_$2">>$PROJECT_ROOT/config.in
+    $MAKE >>$CONFIG_LOG 2>&1 >>$CONFIG_LOG 2>&1
+    if [ -x $1 ] ; then
+        echo -e >&2 "  [${C_GREEN}success${C_NONE}] "
+        echo "DEFINES+=HAVE_$2">>$QMAKE_CACHE
     else
-    	echo -e >&2 "  [${C_RED}failure${C_NONE}] "
+        echo -e >&2 "  [${C_RED}failure${C_NONE}] "
     fi
-
-    [ -f ./$1 ] && rm ./$1
-    $MAKE clean >>$CONFIG_LOG
-    $MAKE distclean >>$CONFIG_LOG
 }
-
-echo >&2 "Installing dependencies."
 
 echo >&2 "Installing QtSoap 2.7_1..."
 cd deps/qtsoap-2.7_1-opensource
@@ -157,17 +247,13 @@ cd deps/qtsoap-2.7_1-opensource
 make &> qtsoap_build.log
 cd ../..
 
-echo >&2 "Testing for external libraries."
+echo >&2 "Testing for optional external libraries."
+echo >&2 "If tests fail, some features will not be available."
 
-configtest qt4     Qt
+configtest qt4 QT
 
-#====finaly running qmake====
+# run qmake
 echo "Autodetection finished. Running qmake."
-cd  $PROJECT_ROOT
-
-[ -f config.pri ] && mv config.pri config.pri.bak
-mv config.in config.pri
-
-$QMAKE_BIN $QMAKE_PARAMS -recursive $PROJECT_ROOT/projects.pro 2>> config.log
-
+cd  $BRISA_BUILD_TREE
+$QMAKE_BIN $QMAKE_PARAMS "$BRISA_SOURCE_TREE/brisa.pro" -recursive >>$CONFIG_LOG
 echo -e >&2 "${C_CYAN}Configure finished. Run $MAKE now.${C_NONE}\n"
